### ISSUE TITLE
Disable RIV mapping of tab and shift-tab 

### ISSUE THREAD

**Issue by lorin** [Rykka/riv.vim#85]
I have my tab key and shift-tab keys remapped to cycle between buffers, like this:

```
:nnoremap <Tab> :bnext<CR>
:nnoremap <S-Tab> :bprevious<CR>
```

When I edit an RST file with RIV, it appears to remap tab to something else (not exactly sure what). How do I disable this behavior so I can still use tab and shift-tab to cycle between buffers?

**Comment by himito** [comment]
Use to disable mapping in insert mode.
let g:riv_ignored_imaps = "<Tab>,<S-Tab>"

**Comment by lorin** [comment]
@himito I'm using tab and shift-tab in command mode. Is there a way to disable those mappings in command mode?

**Comment by himito** [comment]
You mean "normal mode", right ? In that case:

Use to disable mapping in normal mode.
`let g:riv_ignored_nmaps = "<Tab>,<S-Tab>"`

For more information :smile: : [options](https://github.com/Rykka/riv.vim/blob/master/doc/riv_instruction.rst#options )

**Comment by lorin** [comment]
Yes, normal mode (I always forget the name of that mode). Thanks for the pointers to the docs.
