### ISSUE TITLE
Riv2HtmlAndBrowse not work

### ISSUE THREAD

**Issue by uralbash** [Rykka/riv.vim#94]
After that commit https://github.com/Rykka/riv.vim/commit/63ce78b1abd73fd7f0922f497185ef96cc621df4 ``Riv2HtmlAndBrowse`` not work. But all previous work OK.

my OS ``Ubuntu 14.10``, ``vim 7.4``

**Comment by pshchelo** [comment]
+1, recently started experiencing this too

**Comment by wichtounet** [comment]
The same here since I updated my vim plugins.
